/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-AtvTools
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_ATVTOOLS_API_H
#define INCLUDED_ATVTOOLS_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_AtvTools_EXPORTS
#define ATVTOOLS_API __GR_ATTR_EXPORT
#else
#define ATVTOOLS_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_ATVTOOLS_API_H */
