/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(TvDecode.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(06bff7cae3c664c62f4ff54035e16d92)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/AnalogTV/TvDecode.h>
// pydoc.h is automatically generated in the build directory
#include <TvDecode_pydoc.h>

void bind_TvDecode(py::module& m)
{

    using TvDecode = gr::AnalogTV::TvDecode;


    py::class_<TvDecode, gr::block, gr::basic_block, std::shared_ptr<TvDecode>>(
        m, "TvDecode", D(TvDecode))

        .def(py::init(&TvDecode::make), D(TvDecode, make))


        ;
}
