/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(AtvDecoder.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(5c43a601b729c20feed6b508fd5e75c1)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/AtvTools/AtvDecoder.h>
// pydoc.h is automatically generated in the build directory
#include <AtvDecoder_pydoc.h>

void bind_AtvDecoder(py::module& m)
{

    using AtvDecoder    = gr::AtvTools::AtvDecoder;


    py::class_<AtvDecoder, gr::block, gr::basic_block,
        std::shared_ptr<AtvDecoder>>(m, "AtvDecoder", D(AtvDecoder))

        .def(py::init(&AtvDecoder::make),
           py::arg("samp_rate"),
           py::arg("standard"),
           D(AtvDecoder,make)
        )
        



        ;




}








